# Generated by Django 4.2.30 on 2026-10-08 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Globally stable identifier for sync across cloud/school-server.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('actor_email', models.CharField(blank=True, db_index=True, help_text='Snapshot of user email or identifier at time of event.', max_length=255)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('SESSION_REVOKED', 'Session Revoked'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('ACCOUNT_DEACTIVATED', 'Account Deactivated'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ROLE_ASSIGNED', 'Role Assigned'), ('ROLE_REMOVED', 'Role Removed'), ('ROLE_CREATED', 'Role Created'), ('ROLE_UPDATED', 'Role Updated'), ('ROLE_DELETED', 'Role Deleted'), ('PERMISSION_CHANGED', 'Permission Changed')], db_index=True, max_length=64)),
                ('resource_type', models.CharField(blank=True, db_index=True, help_text='Target resource type, e.g. "User", "Role", "Session".', max_length=64)),
                ('resource_id', models.CharField(blank=True, db_index=True, help_text='Target resource primary key or UUID.', max_length=128)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('DENIED', 'Denied')], db_index=True, default='SUCCESS', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Sanitized event metadata. Sensitive values must be scrubbed.')),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'ordering': ['-created_at'],
            },
        ),
    ]
