# Generated by Django 4.2.30 on 2026-10-08 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Globally stable identifier for sync across cloud/school-server.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('codename', models.CharField(db_index=True, help_text='Machine-readable stable identifier, e.g. "students.view".', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable title, e.g. "View Student Profiles".', max_length=150)),
                ('resource', models.CharField(db_index=True, help_text='Resource identifier, e.g. "students", "results", "finance".', max_length=64)),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ARCHIVE', 'Archive'), ('EXPORT', 'Export'), ('APPROVE', 'Approval'), ('PUBLISH', 'Publish'), ('MANAGE', 'Manage')], db_index=True, help_text='Action verb on the resource.', max_length=32)),
                ('description', models.TextField(blank=True, help_text='Detailed explanation of capabilities granted.')),
                ('is_system', models.BooleanField(default=True, help_text='True for standard built-in system permissions.')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'ordering': ['resource', 'action'],
            },
        ),
        migrations.CreateModel(
            name='PermissionScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Globally stable identifier for sync across cloud/school-server.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(choices=[('GLOBAL', 'Global (All)'), ('ASSIGNED_CLASSES', 'Assigned Classes'), ('ASSIGNED_SUBJECTS', 'Assigned Subjects'), ('DEPARTMENT', 'Department'), ('SELECTED_CLASSES', 'Selected Classes'), ('OWN_CHILDREN', 'Own Children'), ('SELF', 'Self Only')], db_index=True, help_text='Machine-readable scope identifier.', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Human-friendly display name for the scope.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Explanation of boundary rules for this scope.')),
                ('is_system', models.BooleanField(default=True, help_text='Indicates whether this is a core built-in scope.')),
            ],
            options={
                'verbose_name': 'permission scope',
                'verbose_name_plural': 'permission scopes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Globally stable identifier for sync across cloud/school-server.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(db_index=True, help_text='Machine-readable role code, e.g. "TEACHER", "BURSAR", "SUPER_ADMIN".', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Human-friendly role name, e.g. "Senior Teacher".', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the role responsibility within the school.')),
                ('is_system', models.BooleanField(default=False, help_text='System roles (e.g. Super Admin, School Admin) cannot be deleted.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive roles do not grant permissions to assigned users.')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Globally stable identifier for sync across cloud/school-server.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('scope_parameters', models.JSONField(blank=True, default=dict, help_text='Optional JSON parameters for parameterized scopes (e.g. {"class_ids": [...]}).')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='permissions.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='permissions.role')),
                ('scope', models.ForeignKey(blank=True, help_text='Boundary scope for this permission. If null, treated as GLOBAL.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_permissions', to='permissions.permissionscope')),
            ],
            options={
                'verbose_name': 'role permission',
                'verbose_name_plural': 'role permissions',
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Globally stable identifier for sync across cloud/school-server.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('assigned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Optional timestamp when this role assignment automatically expires.', null=True)),
                ('scope_context', models.JSONField(blank=True, default=dict, help_text='Contextual scope payload (e.g. {"assigned_class_ids": [1, 2]}).')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_granted', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='permissions.role')),
                ('scope_override', models.ForeignKey(blank=True, help_text='Optional scope override applied across this role assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_overrides', to='permissions.permissionscope')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_assigned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'role assignment',
                'verbose_name_plural': 'role assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='permissions.RolePermission', to='permissions.permission'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['resource', 'action'], name='permissions_resourc_3f188d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='roleassignment',
            unique_together={('user', 'role')},
        ),
    ]
